# Generated by Django 4.2.13 on 2024-12-29 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Meta keywords'),
            preserve_default=False,
        ),
    ]
