name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirement.txt

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy code to server using SSH password
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        # Transfer code to the server (excluding media and venv directories)
        sshpass -p "$PASSWORD" rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude 'media/' --exclude 'venv/' . $USER@$HOST:/var/www/finesurgicalsnepal/finechangesdone/

        # SSH into the server and run deployment steps
        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
        cd /var/www/finesurgicalsnepal/finechangesdone

        # Activate virtual environment
        source /var/www/finesurgicalsnepal/finechangesdone/venv/bin/activate

        # Apply database migrations
        python manage.py migrate

        # Collect static files
        python manage.py collectstatic --noinput

        # Restart Gunicorn service using systemd
        sudo systemctl restart gunicorn
        EOF
